<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sangeeta" failures="1" tests="6" name="com.ninza.crm.campaigntestpractice.Demo" time="0.113" errors="0" timestamp="2025-09-10T17:46:26 IST" skipped="5">
  <testcase classname="com.ninza.crm.campaigntestpractice.Demo" name="add" time="0.015">
    <failure message="expected [hfdc] but found [hdfc]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [hfdc] but found [hdfc]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.ninza.crm.campaigntestpractice.Demo.add(Demo.java:12)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- add -->
  <testcase classname="com.ninza.crm.campaigntestpractice.Demo" name="add" time="0.016">
    <skipped/>
  </testcase> <!-- add -->
  <testcase classname="com.ninza.crm.campaigntestpractice.Demo" name="add" time="0.009">
    <skipped/>
  </testcase> <!-- add -->
  <testcase classname="com.ninza.crm.campaigntestpractice.Demo" name="add" time="0.016">
    <skipped/>
  </testcase> <!-- add -->
  <testcase classname="com.ninza.crm.campaigntestpractice.Demo" name="add" time="0.050">
    <skipped/>
  </testcase> <!-- add -->
  <testcase classname="com.ninza.crm.campaigntestpractice.Demo" name="add" time="0.007">
    <skipped/>
  </testcase> <!-- add -->
</testsuite> <!-- com.ninza.crm.campaigntestpractice.Demo -->
